# --------------------------------------------------
# This file contains setup scripts for the project.
# For more info, see: https://github.com/casey/just
# --------------------------------------------------

set positional-arguments

set shell := ["bash", "-c"]

# Setup virtual environment and install dependencies.
setup-environment:
    uv python install 3.12
    uv venv
    uv pip install -e .[dev]

run-server *args:
    uv run python main.py "$@"

# Runs static checks using global pre-commit configuration.
run-precommit:
    uv run pre-commit run -c ../../.pre-commit-config.yaml \
        --files `git ls-files --cached --others --exclude-standard`
